import { Public_Sans } from "next/font/google";
import "./globals.css";

const publicSans = Public_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Map monospace variable to Public Sans as well to unify all fonts
const publicSansAsMono = Public_Sans({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="dark" lang="en">
      <body className={`${publicSans.variable} ${publicSansAsMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
