import { Public_Sans } from "next/font/google";
import "./globals.css";
import { AlertProvider } from "@/context/AlertContext"

const publicSans = Public_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const publicSansAsMono = Public_Sans({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="" lang="en">
      <body className={`${publicSans.variable} ${publicSansAsMono.variable} antialiased`}>
        <AlertProvider>
        {children}
        </AlertProvider>
      </body>
    </html>
  );
}
